/* This class definitions are generated by Typewriter. Don't try to change it. 
//use this definition in order not to inherit classes:
//
//export class _EntityFilter { 
//    public sortField: string;
//    public sortDirection: number;
//    public pageSize: number;
//    public pageNumber: number;
//}*/

export class _EntityFilter {
public constructor(init?: Partial<_EntityFilter>) {
        Object.assign(this, init);
    }
    public sortField: string;
    public sortDirection: number;
    public pageSize: number;
    public pageNumber: number;
}

