/* This class definitions are generated by Typewriter. Don't try to change it. 
//use this definition in order not to inherit classes:
//
//export class _FormFieldFilter { 
//    public id: number;
//    public _FormId: number;
//    public _FieldId: number;
//    public pageSize: number;
//    public pageNumber: number;
//}*/

export class _FormFieldFilter {
public constructor(init?: Partial<_FormFieldFilter>) {
        Object.assign(this, init);
    }
    public id: number;
    public _FormId: number;
    public _FieldId: number;
    public pageSize: number;
    public pageNumber: number;
}

