/* This class definitions are generated by Typewriter. Don't try to change it. 
//use this definition in order not to inherit classes:
//
//export class _GenericEntityFilter { 
//    public _EntityId: number;
//    public sort_FieldId: number;
//    public sortDirection: number;
//    public pageSize: number;
//    public pageNumber: number;
//}*/

export class _GenericEntityFilter {
public constructor(init?: Partial<_GenericEntityFilter>) {
        Object.assign(this, init);
    }
    public _EntityId: number;
    public sort_FieldId: number;
    public sortDirection: number;
    public pageSize: number;
    public pageNumber: number;
}

