/* This class definitions are generated by Typewriter. Don't try to change it. 
//use this definition in order not to inherit classes:
//
//export class _FieldType { 
// Inherited properties
//    public id: number;
//    public name: string;
//}
//export class _FieldTypeBase { 
//    public id: number;
//    public name: string;
//}*/


export class _FieldTypeBase {
public constructor(init?: Partial<_FieldTypeBase>) {
        Object.assign(this, init);
    }
    public id: number;
    public name: string;
}


export class _FieldType extends _FieldTypeBase {
public constructor(init?: Partial<_FieldType>) {
        super(init);
        Object.assign(this, init);
    }
}
