/* This class definitions are generated by Typewriter. Don't try to change it. 
//use this definition in order not to inherit classes:
//
//export class _FormField { 
// Inherited properties
//    public id: number;
//    public label: string;
//    public _FormId: number;
//    public _FieldId: number;
//    public column: number;
//    public length: number;
//    public row: number;
//    public _FieldTypeId: number;
//}
//export class _FormFieldBase { 
//    public id: number;
//    public label: string;
//    public _FormId: number;
//    public _FieldId: number;
//    public column: number;
//    public length: number;
//    public row: number;
//}*/


export class _FormFieldBase {
public constructor(init?: Partial<_FormFieldBase>) {
        Object.assign(this, init);
    }
    public id: number;
    public label: string;
    public _FormId: number;
    public _FieldId: number;
    public column: number;
    public length: number;
    public row: number;
}


export class _FormField extends _FormFieldBase {
public constructor(init?: Partial<_FormField>) {
        super(init);
        Object.assign(this, init);
    }
    public _FieldTypeId: number;
}
