/* This class definitions are generated by Typewriter. Don't try to change it. 
//use this definition in order not to inherit classes:
//
//export class _TestEntity { 
// Inherited properties
//    public id: number;
//    public name: string;
//    public date: Date;
//}
//export class _TestEntityBase { 
//    public id: number;
//    public name: string;
//    public date: Date;
//}*/


export class _TestEntityBase {
public constructor(init?: Partial<_TestEntityBase>) {
        Object.assign(this, init);
    }
    public id: number;
    public name: string;
    public date: Date;
}


export class _TestEntity extends _TestEntityBase {
public constructor(init?: Partial<_TestEntity>) {
        super(init);
        Object.assign(this, init);
    }
}
