/* This class definitions are generated by Typewriter. Don't try to change it. 
//use this definition in order not to inherit classes:
//
//export class _Entity { 
// Inherited properties
//    public id: number;
//    public name: string;
//    public databaseName: string;
//    public databaseScheme: string;
//}
//export class _EntityBase { 
//    public id: number;
//    public name: string;
//    public databaseName: string;
//    public databaseScheme: string;
//}*/


export class _EntityBase {
    public id: number;
    public name: string;
    public databaseName: string;
    public databaseScheme: string;
}


export class _Entity extends _EntityBase { 
}
