/* This class definitions are generated by Typewriter. Don't try to change it. 
//use this definition in order not to inherit classes:
//
//export class _Field { 
// Inherited properties
//    public id: number;
//    public _FieldTypeId: number;
//    public _EntityId: number;
//    public name: string;
//    public databaseName: string;
//    public _EntityName: string;
//}
//export class _FieldBase { 
//    public id: number;
//    public _FieldTypeId: number;
//    public _EntityId: number;
//    public name: string;
//    public databaseName: string;
//}*/


export class _FieldBase {
    public id: number;
    public _FieldTypeId: number;
    public _EntityId: number;
    public name: string;
    public databaseName: string;
}


export class _Field extends _FieldBase { 
    public _EntityName: string;
}
