/* This class definitions are generated by Typewriter. Don't try to change it. 
//use this definition in order not to inherit classes:
//
//export class _Field { 
// Inherited properties
//    public id: number;
//    public _FieldTypeId: number;
//    public _EntityId: number;
//    public name: string;
//    public databaseName: string;
//    public _EntityName: string;
//    public _FieldTypeName: string;
//}
//export class _FieldBase { 
//    public id: number;
//    public _FieldTypeId: number;
//    public _EntityId: number;
//    public name: string;
//    public databaseName: string;
//}*/


export class _FieldBase {
public constructor(init?: Partial<_FieldBase>) {
        Object.assign(this, init);
    }
    public id: number;
    public _FieldTypeId: number;
    public _EntityId: number;
    public name: string;
    public databaseName: string;
}


export class _Field extends _FieldBase {
public constructor(init?: Partial<_Field>) {
        super(init);
        Object.assign(this, init);
    }
    public _EntityName: string;
    public _FieldTypeName: string;
}
