/* This class definitions are generated by Typewriter. Don't try to change it. 
//use this definition in order not to inherit classes:
//
//export class _Form { 
// Inherited properties
//    public id: number;
//    public name: string;
//    public _EntityId: number;
//}
//export class _FormBase { 
//    public id: number;
//    public name: string;
//    public _EntityId: number;
//}*/


export class _FormBase {
public constructor(init?: Partial<_FormBase>) {
        Object.assign(this, init);
    }
    public id: number;
    public name: string;
    public _EntityId: number;
}


export class _Form extends _FormBase {
public constructor(init?: Partial<_Form>) {
        super(init);
        Object.assign(this, init);
    }
}
