${ 
    Template(Settings settings)
    {
        settings
            .IncludeCurrentProject()
            .IncludeProject("FRI3NDS.Angular4Template.Core");
        settings.OutputExtension = ".ts";
    }
}/* This class definitions are generated by Typewriter. Don't try to change it.*/$Enums(FRI3NDS.Angular4Template.Core.Models.Enums*)[
export enum $Name {$Values[
	$Name = $Value][,]
}]