/* This class definitions are generated by Typewriter. Don't try to change it. 
//use this definition in order not to inherit classes:
//
//export class _FieldFilter { 
//    public _EntityId: number;
//}*/

export class _FieldFilter {
    public _EntityId: number;
}

